### ISSUE TITLE
keras_contrib报错

### ISSUE THREAD

**Issue by huaji1992** [msgi/nlp-journey#6]
2020-04-24 11:14:12.760618: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-04-24 11:14:12.760859: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Using TensorFlow backend.
2020-04-24 11:14:17.101006: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-04-24 11:14:17.535028: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 1050 computeCapability: 6.1
coreClock: 1.493GHz coreCount: 5 deviceMemorySize: 4.00GiB deviceMemoryBandwidth: 104.43GiB/s
2020-04-24 11:14:17.537454: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-04-24 11:14:17.539765: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cublas64_10.dll'; dlerror: cublas64_10.dll not found
2020-04-24 11:14:17.541926: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cufft64_10.dll'; dlerror: cufft64_10.dll not found
2020-04-24 11:14:17.544355: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'curand64_10.dll'; dlerror: curand64_10.dll not found
2020-04-24 11:14:17.547207: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cusolver64_10.dll'; dlerror: cusolver64_10.dll not found
2020-04-24 11:14:17.549591: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cusparse64_10.dll'; dlerror: cusparse64_10.dll not found
2020-04-24 11:14:17.554696: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-04-24 11:14:17.554892: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1592] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-04-24 11:14:17.555937: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-04-24 11:14:17.556583: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-24 11:14:17.556732: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      
Traceback (most recent call last):
  File "c:\Users\Administrator\Desktop\keras_ner\ner.py", line 163, in <module>
    ner = BiLSTMCRFNamedEntityRecognition('model/crf.h5', 'model/config.pkl', train=True, file_path='data/')
  File "c:\Users\Administrator\Desktop\keras_ner\ner.py", line 73, in __init__
    self.model = self.train()
  File "c:\Users\Administrator\Desktop\keras_ner\ner.py", line 77, in train
    model = self.__build_model()
  File "c:\Users\Administrator\Desktop\keras_ner\ner.py", line 134, in __build_model
    model.add(crf)
  File "D:\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\training\tracking\base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "D:\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\sequential.py", line 161, in add
    'Found: ' + str(layer))
TypeError: The added layer must be an instance of class Layer. Found: <keras_contrib.layers.crf.CRF object at 0x0000018943E28A58>

Keras                2.3.1
keras-contrib        2.0.8
tensorflow           2.1.0

你好，你的版本是这些吗

**Comment by msgi** [comment]
keras-contrib 只能跟Keras一起使用，并不支持tensorflow2.0，我回头改一下代码
