### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0,77] = -1 is not in [0, 49) [Op:GatherV2]

### ISSUE THREAD

**Issue by huaji1992** [msgi/nlp-journey#7]
tf.Tensor(
[[  57  327  630 ...    0    0    0]
 [ 850 1979 2299 ...    0    0    0]
 [ 474  814   91 ...    0    0    0]
 ...
 [  44  110  881 ...    0    0    0]
 [   0   33  825 ...    0    0    0]
 [1787 1895  119 ...    0    0    0]], shape=(64, 100), dtype=int32)
tf.Tensor(
[[ 0  0  0 ... -1 -1 -1]
 [ 1  2  2 ... -1 -1 -1]
 [ 0  0  0 ... -1 -1 -1]
 ...
 [ 0  0  3 ... -1 -1 -1]
 [ 0  0  0 ... -1 -1 -1]
 [ 3  4  0 ... -1 -1 -1]], shape=(64, 100), dtype=int32)
Traceback (most recent call last):
  File "c:\Users\Administrator\Desktop\keras_ner\ner.py", line 213, in <module>
    file_path='data')
  File "c:\Users\Administrator\Desktop\keras_ner\ner.py", line 77, in __init__
    self.model = self.train()
  File "c:\Users\Administrator\Desktop\keras_ner\ner.py", line 103, in train
    loss, logits, text_lens = self.train_one_step(model, optimizer, text_batch, labels_batch)
  File "c:\Users\Administrator\Desktop\keras_ner\ner.py", line 117, in train_one_step
    logits, text_lens, log_likelihood = model(text_batch, labels_batch, training=True)
  File "D:\anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 822, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "c:\Users\Administrator\Desktop\keras_ner\ner.py", line 41, in call
    log_likelihood, self.transition_params = ta.text.crf_log_likelihood(logits, label_sequences, text_lens)
  File "D:\anaconda3\lib\site-packages\tensorflow_addons\text\crf.py", line 214, in crf_log_likelihood
    inputs, tag_indices, sequence_lengths, transition_params
  File "D:\anaconda3\lib\site-packages\tensorflow_addons\text\crf.py", line 77, in crf_sequence_score
    return tf.cond(tf.equal(tf.shape(inputs)[1], 1), _single_seq_fn, _multi_seq_fn)
  File "D:\anaconda3\lib\site-packages\tensorflow_core\python\ops\control_flow_ops.py", line 1389, in cond_for_tf_v2
    return cond(pred, true_fn=true_fn, false_fn=false_fn, strict=True, name=name)
  File "D:\anaconda3\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "D:\anaconda3\lib\site-packages\tensorflow_core\python\ops\control_flow_ops.py", line 1204, in cond
    result = false_fn()
  File "D:\anaconda3\lib\site-packages\tensorflow_addons\text\crf.py", line 72, in _multi_seq_fn
    tag_indices, sequence_lengths, transition_params
  File "D:\anaconda3\lib\site-packages\tensorflow_addons\text\crf.py", line 291, in crf_binary_score
    binary_scores = tf.gather(flattened_transition_params, flattened_transition_indices)
  File "D:\anaconda3\lib\site-packages\tensorflow_core\python\util\dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "D:\anaconda3\lib\site-packages\tensorflow_core\python\ops\array_ops.py", line 4125, in gather_v2
    batch_dims=batch_dims)
  File "D:\anaconda3\lib\site-packages\tensorflow_core\python\util\dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "D:\anaconda3\lib\site-packages\tensorflow_core\python\ops\array_ops.py", line 4108, in gather
    return gen_array_ops.gather_v2(params, indices, axis, name=name)
  File "D:\anaconda3\lib\site-packages\tensorflow_core\python\ops\gen_array_ops.py", line 3683, in gather_v2
    _ops.raise_from_not_ok_status(e, name)
  File "D:\anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 6606, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0,77] = -1 is not in [0, 49) [Op:GatherV2]

大神，这是数据集问题吗？

**Comment by msgi** [comment]
之前有个bug，还没来得及上传，现在可以了

**Comment by msgi** [comment]
之前有个bug,没有及时上传，现在可以了
